In [1]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}


Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.


In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

In [0]:
#unzip Autopilot folder as data is inside there
!cp  /content/drive/Hackthon/Innoplexus/temp/* .
#!cp new_html.csv  /content/drive/Hackthon/Innoplexus/

In [4]:
#!unzip train.zip
#!unzip glove.6B.zip

Archive:  train.zip
  inflating: train.csv               
  inflating: html_data.csv           
Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [202]:
!ls

datalab			   Innoplexus_train_02.ipynb
drive			   LSTM_Innoplexus_train_03.ipynb
glove.6B.100d.txt	   new_data.csv
glove.6B.200d.txt	   new_html.csv
glove.6B.300d.txt	   sample_submission_poy1UIu.csv
glove.6B.50d.txt	   test_nvPHrOx.csv
glove.6B.zip		   test_predicted.csv
gru_100_ep_30_model.h5	   train.csv
html_data.csv		   train.zip
Innoplexus_train_01.ipynb


In [0]:
#!cp glove.6B.100d.txt  /content/drive/Hackthon/Innoplexus/temp/

In [2]:
import pandas as pd
import numpy as np
import re
from keras.models import Sequential
from keras.layers import Dropout
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical
from keras.layers import Dense, Input,  Flatten
from keras.layers import Conv1D, MaxPooling1D, AveragePooling1D, Embedding

from keras.callbacks import ModelCheckpoint
from sklearn.metrics import confusion_matrix

from numpy.random import RandomState
from sklearn.preprocessing import LabelEncoder
from keras.layers import LSTM,GRU
SEED = RandomState(1234567890)

Using TensorFlow backend.


In [0]:
with open('new_data.csv', encoding='ascii', errors='ignore') as infile:
    Data = pd.read_csv(infile)
Data_Train = pd.read_csv("train.csv")
Data_Test  = pd.read_csv("test_nvPHrOx.csv")

In [4]:
Data.shape

(79345, 2)

In [0]:
def url_str_conv(s):
  #ss =re.sub('http://\w.*/','',s)
  #ss =re.sub('https://\w.*/','',s)
  i1 = s.find("//")
  i2 = s.find("/",i1+2)
  if i1==-1 or i2 == -1:
    i3 = s.find(".com")
    ss = s[i1+2:i3]
    ss =re.sub('www.','',ss)
    #print(ss)
    ss =re.findall(r'\w\w+',ss)
    ss = ' '.join(ss)
    return ss
  ss = s[i2+1:]
  ss =re.sub('www.','',ss)
  ss =re.findall(r'\w\w+',ss)
  ss = ' '.join(ss)
  return ss

In [0]:
def title_text(s):
  s = str(s)
  ss =re.sub('\d',' ',s)
  ss =re.findall(r'\w\w+',ss)
  ss = ' '.join(ss)
  ss = ss.strip()
  return ss

In [7]:
q= 'https://www.clinicaltrialsregister.eu/ctr-search/trial/2006-006214-16/GB'
title_text(q)

'https www clinicaltrialsregister eu ctr search trial GB'

In [0]:
Data['new_title'] = list(map(title_text,Data.Title))
Data_Train['new_url'] = list(map(url_str_conv,Data_Train.Url))
Data_Test['new_url'] = list(map(url_str_conv,Data_Test.Url))
#

In [0]:
Data_Train = pd.merge(Data_Train,Data,how="left",on="Webpage_id",)
Data_Test = pd.merge(Data_Test,Data,how="left",on="Webpage_id")
#Data_Train.drop(columns=["Title_y","new_Title_y"])

In [0]:
def fill_empty(new_title,new_url):
    if len(new_title) < 2:
      return new_url
    else:
      return new_title
      

In [0]:
Data_Train["update_title"] = list(map(fill_empty,Data_Train.new_title,Data_Train.new_url))
Data_Test["update_title"] = list(map(fill_empty,Data_Test.new_title,Data_Test.new_url))

In [12]:
Data_Train.head()

Webpage_id                Domain  \
0           1  www.fiercepharma.com   
1           2  www.fiercepharma.com   
2           3  www.fiercepharma.com   
3           4  www.fiercepharma.com   
4           5  www.fiercepharma.com   

                                                 Url   Tag  \
0  http://www.fiercepharma.com/marketing/tecfider...  news   
1  http://www.fiercepharma.com/pharma/novo-equipp...  news   
2  http://www.fiercepharma.com/pharma/another-exe...  news   
3  http://www.fiercepharma.com/pharma/teva-buy-bi...  news   
4  http://www.fiercepharma.com/marketing/actress-...  news   

                                             new_url  \
0  marketing tecfidera gilenya and aubagio way ba...   
1  pharma novo equipped to weather storm diabetes...   
2  pharma another exec departs troubled endo and ...   
3  pharma teva buy biosim specialist celltrion it...   
4  marketing actress marissa tomei partners aller...   

                                               Title  \
0  Tecfidera, Gilenya and Aubagio&#039;s 3-way ba...   
1  novo equipped to weather the storm in the u.s....   
2  another exec departs troubled endo--and this t...   
3  would teva buy korea&#039;s celltrion to beef ...   
4  restasis-maker allergan recruits actress maris...   

                                           new_title  \
0  Tecfidera Gilenya and Aubagio way battle for M...   
1  novo equipped to weather the storm in the diab...   
2  another exec departs troubled endo and this ti...   
3  would teva buy korea celltrion to beef up in b...   
4  restasis maker allergan recruits actress maris...   

                                        update_title  
0  Tecfidera Gilenya and Aubagio way battle for M...  
1  novo equipped to weather the storm in the diab...  
2  another exec departs troubled endo and this ti...  
3  would teva buy korea celltrion to beef up in b...  
4  restasis maker allergan recruits actress maris...

In [0]:
Data_Train.sort_values('Tag',inplace=True)

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
def tokenize_data(X_raw, Y_raw):
    tokenizer = Tokenizer(num_words=MAX_NB_WORDS)
    tokenizer.fit_on_texts(X_raw)
    sequences = tokenizer.texts_to_sequences(X_raw)
    word_index = tokenizer.word_index
    X_processed = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
    label_encoder_y = LabelEncoder()
    Y_processed=to_categorical(label_encoder_y.fit_transform(Y_raw))

    return X_processed, Y_processed, word_index,tokenizer,label_encoder_y

In [0]:
def tokenize_test_data(X_raw, tokenizer):
    sequences = tokenizer.texts_to_sequences(X_raw)
    word_index = tokenizer.word_index
    X_processed = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)

    return X_processed,word_index

In [0]:
def split_the_data(X_processed, Y_processed):
  count=1
  #X=list(X_processed)
  #Y=list(Y_processed)
  x_train=[]
  y_train=[]
  x_val=[]
  y_val=[]
  for i,j in zip(X_processed,Y_processed):
    if count%3==0:
      x_val.append(i)
      y_val.append(j)
    else:
      x_train.append(i)
      y_train.append(j)
    count+=1
  x_train=np.asarray(x_train)
  x_val=np.asarray(x_val)
  y_train=np.asarray(y_train)
  y_val=np.asarray(y_val)
  return x_train, x_val, y_train, y_val

In [0]:
def make_embedding_layer(word_index):
    embeddings = get_embeddings()
    nb_words = min(MAX_NB_WORDS, len(word_index))
    embedding_matrix = np.zeros((nb_words, EMBEDDING_DIM))

    for word, i in word_index.items():
        if i >= MAX_NB_WORDS:
            continue
        embedding_vector = embeddings.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

    embedding_layer = Embedding(nb_words, EMBEDDING_DIM, weights=[embedding_matrix], input_length=MAX_SEQUENCE_LENGTH, trainable=False)
    return embedding_layer

In [0]:
def get_embeddings():
    embeddings = {}
    with open(GLOVE_FILE, 'r') as f:
        for line in f:
            values = line.split()
            word = values[0]
            coefs = np.asarray(values[1:], dtype='float32')
            embeddings[word] = coefs
    return embeddings

In [0]:
MAX_SEQUENCE_LENGTH = 50
MAX_NB_WORDS = 10000
EMBEDDING_DIM = 200
GLOVE_FILE = 'glove.6B.200d.txt'

In [0]:
X_processed, Y_processed, word_index,tokenizer,label_encoder_y = tokenize_data(Data_Train.update_title,Data_Train.Tag)
x_train, x_val, y_train, y_val = split_the_data(X_processed, Y_processed)
embedded_sequences = make_embedding_layer(word_index)


In [0]:
def make_model_lstm(labels_index, embedded_sequences,drop_rate=0.5,unit=100,dense=256):
   
    model = Sequential([
        embedded_sequences,
        LSTM(unit),
        #LSTM(100),
        #Flatten(),
        Dropout(drop_rate),
        Dense(dense, activation='relu'),
        Dropout(drop_rate),
        Dense(64, activation='relu'),
        Dense(labels_index, activation='softmax')
    ])

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

    return model

In [0]:
def make_model_gru(labels_index, embedded_sequences,drop_rate=0.5,unit=100,dense=256):
    
    model = Sequential([
        embedded_sequences,
        GRU(unit),
        #GRU(50),
        #Flatten(),
        Dropout(drop_rate),
        Dense(dense, activation='relu'),
        Dropout(drop_rate),
        Dense(64, activation='relu'),
        Dense(labels_index, activation='softmax')
    ])

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

    return model

In [34]:
labels_index=9
model = make_model_lstm(labels_index, embedded_sequences,drop_rate=0.3,unit=50,dense=100)
model.fit(x_train, y_train, validation_data=(x_val, y_val),epochs=10, batch_size=128,)

Train on 35632 samples, validate on 17815 samples
Epoch 1/10
35632/35632 [==============================] - 42s 1ms/step - loss: 1.1396 - acc: 0.6045 - val_loss: 0.6765 - val_acc: 0.7717
Epoch 2/10
35632/35632 [==============================] - 40s 1ms/step - loss: 0.6826 - acc: 0.7726 - val_loss: 0.5467 - val_acc: 0.8196
Epoch 3/10
35632/35632 [==============================] - 40s 1ms/step - loss: 0.5731 - acc: 0.8097 - val_loss: 0.4884 - val_acc: 0.8394
Epoch 4/10
35632/35632 [==============================] - 40s 1ms/step - loss: 0.5023 - acc: 0.8328 - val_loss: 0.4488 - val_acc: 0.8538
Epoch 5/10
35632/35632 [==============================] - 40s 1ms/step - loss: 0.4567 - acc: 0.8481 - val_loss: 0.4252 - val_acc: 0.8598
Epoch 6/10
35632/35632 [==============================] - 40s 1ms/step - loss: 0.4223 - acc: 0.8614 - val_loss: 0.4066 - val_acc: 0.8707
Epoch 7/10
35632/35632 [==============================] - 40s 1ms/step - loss: 0.3952 - acc: 0.8704 - val_loss: 0.4003 - val_acc

In [25]:
labels_index=9
model = make_model_lstm(labels_index, embedded_sequences,drop_rate=0.8,unit=500,dense=100)
model.fit(x_train, y_train, validation_data=(x_val, y_val),epochs=15, batch_size=256,)
model = make_model_lstm(labels_index, embedded_sequences,drop_rate=0.7,unit=500,dense=500)
model.fit(x_train, y_train, validation_data=(x_val, y_val),epochs=15, batch_size=256,)
model = make_model_lstm(labels_index, embedded_sequences,drop_rate=0.6,unit=500,dense=500)
model.fit(x_train, y_train, validation_data=(x_val, y_val),epochs=15, batch_size=256,)
model = make_model_lstm(labels_index, embedded_sequences,drop_rate=0.3,unit=50,dense=100)
model.fit(x_train, y_train, validation_data=(x_val, y_val),epochs=15, batch_size=256,)


Train on 35632 samples, validate on 17815 samples
Epoch 1/15
35632/35632 [==============================] - 48s 1ms/step - loss: 1.4153 - acc: 0.4990 - val_loss: 0.9163 - val_acc: 0.6955
Epoch 2/15
35632/35632 [==============================] - 46s 1ms/step - loss: 0.9440 - acc: 0.6740 - val_loss: 0.7370 - val_acc: 0.7491
Epoch 3/15
35632/35632 [==============================] - 46s 1ms/step - loss: 0.7898 - acc: 0.7320 - val_loss: 0.6355 - val_acc: 0.7884
Epoch 4/15
35632/35632 [==============================] - 46s 1ms/step - loss: 0.7058 - acc: 0.7633 - val_loss: 0.5988 - val_acc: 0.8006
Epoch 5/15
35632/35632 [==============================] - 46s 1ms/step - loss: 0.6372 - acc: 0.7863 - val_loss: 0.5534 - val_acc: 0.8191
Epoch 6/15
35632/35632 [==============================] - 46s 1ms/step - loss: 0.5831 - acc: 0.8059 - val_loss: 0.5097 - val_acc: 0.8315
Epoch 7/15
35632/35632 [==============================] - 46s 1ms/step - loss: 0.5478 - acc: 0.8205 - val_loss: 0.5044 - val_acc

In [26]:
model = make_model_gru(labels_index, embedded_sequences,drop_rate=0.8,unit=500,dense=500)
model.fit(x_train, y_train, validation_data=(x_val, y_val),epochs=15, batch_size=256,)
model = make_model_gru(labels_index, embedded_sequences,drop_rate=0.7,unit=500,dense=500)
model.fit(x_train, y_train, validation_data=(x_val, y_val),epochs=15, batch_size=256,)
model = make_model_gru(labels_index, embedded_sequences,drop_rate=0.6,unit=500,dense=500)
model.fit(x_train, y_train, validation_data=(x_val, y_val),epochs=15, batch_size=256,)
model = make_model_gru(labels_index, embedded_sequences,drop_rate=0.3,unit=50,dense=100)
model.fit(x_train, y_train, validation_data=(x_val, y_val),epochs=15, batch_size=256,)

Train on 35632 samples, validate on 17815 samples
Epoch 1/15
35632/35632 [==============================] - 38s 1ms/step - loss: 1.4521 - acc: 0.4805 - val_loss: 0.8922 - val_acc: 0.6980
Epoch 2/15
35632/35632 [==============================] - 36s 1ms/step - loss: 0.9273 - acc: 0.6775 - val_loss: 0.6930 - val_acc: 0.7653
Epoch 3/15
35632/35632 [==============================] - 36s 1ms/step - loss: 0.7524 - acc: 0.7463 - val_loss: 0.6137 - val_acc: 0.7938
Epoch 4/15
35632/35632 [==============================] - 36s 1ms/step - loss: 1.1539 - acc: 0.6551 - val_loss: 0.6321 - val_acc: 0.7967
Epoch 5/15
35632/35632 [==============================] - 36s 1ms/step - loss: 0.8613 - acc: 0.7252 - val_loss: 0.6307 - val_acc: 0.8009
Epoch 6/15
35632/35632 [==============================] - 36s 1ms/step - loss: 0.6544 - acc: 0.7868 - val_loss: 0.5323 - val_acc: 0.8314
Epoch 7/15
35632/35632 [==============================] - 36s 1ms/step - loss: 0.5671 - acc: 0.8161 - val_loss: 0.5007 - val_acc

In [304]:
labels_index=9
model = make_model_lstm(labels_index, embedded_sequences)
model.fit(x_train, y_train, validation_data=(x_val, y_val),epochs=15, batch_size=256,)

Train on 35632 samples, validate on 17815 samples
Epoch 1/15
35632/35632 [==============================] - 49s 1ms/step - loss: 1.2531 - acc: 0.5594 - val_loss: 0.7998 - val_acc: 0.7223
Epoch 2/15
35632/35632 [==============================] - 46s 1ms/step - loss: 0.7893 - acc: 0.7295 - val_loss: 0.6579 - val_acc: 0.7749
Epoch 3/15
35632/35632 [==============================] - 47s 1ms/step - loss: 0.6695 - acc: 0.7720 - val_loss: 0.5605 - val_acc: 0.8152
Epoch 4/15
35632/35632 [==============================] - 47s 1ms/step - loss: 0.5867 - acc: 0.8035 - val_loss: 0.5098 - val_acc: 0.8327
Epoch 5/15
35632/35632 [==============================] - 47s 1ms/step - loss: 0.5408 - acc: 0.8212 - val_loss: 0.5116 - val_acc: 0.8333
Epoch 6/15
35632/35632 [==============================] - 47s 1ms/step - loss: 0.5103 - acc: 0.8362 - val_loss: 0.4490 - val_acc: 0.8556
Epoch 7/15
35632/35632 [==============================] - 47s 1ms/step - loss: 0.4390 - acc: 0.8544 - val_loss: 0.4273 - val_acc

In [35]:
model.save("gru_100_ep_30_model.h5")
!cp gru_100_ep_30_title_model.h5  /content/drive/Hackthon/Innoplexus/

cp: cannot stat 'gru_100_ep_30_title_model.h5': No such file or directory


In [0]:
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score

In [0]:
s = [np.argmax(y, axis=None, out=None) for y in y_val]

In [0]:
#pre_train = model.predict_classes(x_train)
pre_val = model.predict_classes(x_val)

In [39]:
print(f1_score(s,pre_val,average='weighted'))
print(confusion_matrix(s,pre_val,))

0.8805022959015671
[[ 903    9    1    0   11    1    0   19    2]
 [   6 1327    0    1   43   77    2   91    8]
 [   6    1 1416    0   29   40    1    5    3]
 [   3    7    1  380    2   19    2   29    0]
 [  19   29   41   25 2112  316   17   81   24]
 [  78   57   34   10  334 5125   68   77   23]
 [  53    5    2    0   10  122 1530   10    0]
 [  20   38    6    8   31   86    2 2347   30]
 [   0    3    1    0   15   13    0   19  549]]


In [0]:
#Data_test = pd.read_csv("test_nvPHrOx.csv")

In [42]:
Data_Test.shape

(25787, 7)

In [43]:
Data_Test.head()

Webpage_id                         Domain  \
0          31                     isrctn.com   
1          32  www.clinicaltrialsregister.eu   
2          33  www.clinicaltrialsregister.eu   
3          34  www.clinicaltrialsregister.eu   
4          35  www.clinicaltrialsregister.eu   

                                                 Url  \
0               http://www.isrctn.com/ISRCTN57801413   
1  https://www.clinicaltrialsregister.eu/ctr-sear...   
2  https://www.clinicaltrialsregister.eu/ctr-sear...   
3  https://www.clinicaltrialsregister.eu/ctr-sear...   
4  https://www.clinicaltrialsregister.eu/ctr-sear...   

                              new_url  \
0                      ISRCTN57801413   
1  ctr search trial 2006 006214 16 GB   
2  ctr search trial 2006 004265 34 LT   
3  ctr search trial 2010 022183 12 IT   
4  ctr search trial 2010 021349 36 NL   

                                               Title  \
0  isrctn - isrctn57801413: development and valid...   
1                           clinical trials register   
2                           clinical trials register   
3                           clinical trials register   
4                           clinical trials register   

                                           new_title  \
0  isrctn isrctn development and validation of ca...   
1                           clinical trials register   
2                           clinical trials register   
3                           clinical trials register   
4                           clinical trials register   

                                        update_title  
0  isrctn isrctn development and validation of ca...  
1                           clinical trials register  
2                           clinical trials register  
3                           clinical trials register  
4                           clinical trials register

In [0]:

#Data_test['new_url'] = list(map(url_str_conv,Data_test.Url))


In [0]:
x_test,word_index = tokenize_test_data(Data_Test['update_title'], tokenizer)

In [47]:
type(x_test)

numpy.ndarray

In [0]:
y_test = model.predict_classes(x_test)

In [49]:
s =label_encoder_y.inverse_transform(list(y_test))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [50]:
s

array(['clinicalTrials', 'clinicalTrials', 'clinicalTrials', ...,
       'others', 'others', 'others'], dtype=object)

In [0]:
Data_Test["Tag"] = s

In [0]:
Data_Test.to_csv("test_predicted_GRU.csv",index=False,columns=['Webpage_id',"Tag"])

In [0]:
from google.colab import files
files.download("test_predicted_GRU.csv")